### ISSUE TITLE
[Gargantua] One-Time Access Codes

### ISSUE THREAD

**Issue by jggoebel** [svalabs/ui#15]
We should implement a feature where a fixed number of One-Time Access Codes (OTAC) are generated for an ScheduledEvent.
With a OTAC a user can join an event, but only if this OTAC has not been used.

So for 5 generated OTACs, 5 users can join the event.

Maybe the OTAC can reference to the "real" access-code and provide an additional field "used" as well as a timestamp for when it was used.
This way we can first get all OTACs for a user, then the ACs for this OTACs, together with the normal ACs this will define which scenarios the user can see.

This could be used for licensing purposes.

Another great option would be to "invite" users to an event, so first add the user to the event -> the user sees the event without ever editing an access code. This could also be done with OTACs,  just create a new OTAC with "used" flag and add it to the users OTAC-List

MAYBE we could also limit the usage of normal Access Codes (So that a single AC can be entered 5 times an we do not need different OTACs, this is not so good for licensing to single persons, but like floating licenses)

**Comment by yosefha** [comment]
For now I edited the accesscode.go in which I added a new struct as Object to count the quantity and count the used accesscodes. Further I added a Map to save the generated Keys (Access Codes) and two functions to generate those Access Codes and Update the used ones.

I also add a function, to create a Timestamp to see when the access code was used.
